### ISSUE TITLE
Create a tutorial for the package

### ISSUE THREAD

**Issue by chenyu-psy** [coglabuzh/online-exps#12]
Hello,

Could you please include a tutorial on how to use this package in the readme file? For example, explain how to install it using the `npm` function and how to install the development version from Github (if possible). If it has not been published yet, could you also provide instructions on how to download a single function and implement it in our own experiment?

**Comment by ajit283** [comment]
Hi Chenyu,

I have decided to add everything that is relevant for the library user in README.md, while adding everything related to library development in CONTRIBUTING.md.

- Instructions for installing this library from npm are now part of README.md
- Instructions for developing locally and using the local version are in CONTRIBUTING.md (in the chapter "Previewing Results").

Let me know if you are fine with this setup!

**Comment by chenyu-psy** [comment]
Hi Ajit,

Thank you for your work. It makes sense to me. Let's keep doing it until someone has a better suggestion.
