### ISSUE TITLE
Using Javascript Variable in external HTML

### ISSUE THREAD

**Issue by chenyu-psy** [coglabuzh/online-exps#15]
Hello Ajit,

In our template we have an external html called [consent](https://github.com/coglabuzh/jspsych-template/blob/main/assets/external-html/consent.html). I wonder, could we also import global variables here and only need to set the researcher's name, email address, and duration of the experiment in `settings.ts`?

![image](https://github.com/coglabuzh/online-exps/assets/57704488/03026b56-cc88-4da4-b4af-09fb5dc94744)

**Comment by ajit283** [comment]
Dear Chenyu, good idea! I will create a simulus function for this

**Comment by ajit283** [comment]
Hi, I have added it to the stimuli functions (consentScreen). Four arguments can be passed in:

![image](https://github.com/coglabuzh/online-exps/assets/55892788/19f42f3a-d8ee-4bc3-ab9c-2c4ec11e3ce5)
