### ISSUE TITLE
The failed attention check is not recorded.

### ISSUE THREAD

**Issue by chenyu-psy** [coglabuzh/online-exps#17]
There is a system variable `FAILED_ATTENTION_CHECK` used to record whether the participants end the experiment because of completion or failure of attention check. This variable is not used in the current version of attention check function.

**Comment by ajit283** [comment]
Dear Chenyu, thanks for noticing, I will look into this!

**Comment by ajit283** [comment]
Dear Chenyu, I have fixed the function so that it sets the variable correctly. Additionally, I noticed some errors with how the functions is used in the default experiment and fixed those.

**Comment by chenyu-psy** [comment]
Thank you for your effort!
